// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project2

#ifndef _SQUARELINE_PROJECT2_UI_H
#define _SQUARELINE_PROJECT2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Roller2;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_Bar2;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui____initial_actions0;






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
