// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.2.0
// Project name: SquareLine_Project2

#include "ui.h"
//#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Roller2;
lv_obj_t *ui_Switch2;
lv_obj_t *ui_Switch1;
lv_obj_t *ui_Bar2;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Button1;
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_list;
lv_obj_t *ui____initial_actions0;
extern lv_indev_t * indev_keypad;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
	ui_Screen1 = lv_obj_create(NULL);
	lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

	ui_Roller2 = lv_roller_create(ui_Screen1);
	lv_roller_set_options( ui_Roller2, "Tools\nSettings\nVPN", LV_ROLLER_MODE_NORMAL );
	lv_obj_set_width( ui_Roller2, 64);
	lv_obj_set_height( ui_Roller2, 57);
	lv_obj_set_x( ui_Roller2, -29 );
	lv_obj_set_y( ui_Roller2, 3 );
	lv_obj_set_align( ui_Roller2, LV_ALIGN_TOP_MID );
	lv_obj_set_style_text_color(ui_Roller2, lv_color_hex(0xC84141), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_text_opa(ui_Roller2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_text_letter_space(ui_Roller2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_text_line_space(ui_Roller2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui_Roller2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Roller2, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x45AC82), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_bg_opa(ui_Roller2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_border_color(ui_Roller2, lv_color_hex(0x0F7C8D), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_border_opa(ui_Roller2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_outline_color(ui_Roller2, lv_color_hex(0x64ACCC), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_outline_opa(ui_Roller2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_outline_width(ui_Roller2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_outline_pad(ui_Roller2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

	lv_obj_set_style_text_color(ui_Roller2, lv_color_hex(0x1A090B), LV_PART_SELECTED | LV_STATE_DEFAULT );
	lv_obj_set_style_text_opa(ui_Roller2, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT );
	lv_obj_set_style_bg_opa(ui_Roller2, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
	lv_obj_set_style_border_color(ui_Roller2, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
	lv_obj_set_style_border_opa(ui_Roller2, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_Roller2, 1, LV_PART_SELECTED| LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_color(ui_Roller2, lv_color_hex(0x330C0C), LV_PART_SELECTED | LV_STATE_DEFAULT );
	lv_obj_set_style_shadow_opa(ui_Roller2, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui_Roller2, 1, LV_PART_SELECTED| LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_spread(ui_Roller2, 1, LV_PART_SELECTED| LV_STATE_DEFAULT);

	ui_Switch2 = lv_switch_create(ui_Screen1);
	lv_obj_set_width( ui_Switch2, 40);
	lv_obj_set_height( ui_Switch2, 20);
	lv_obj_set_x( ui_Switch2, 33 );
	lv_obj_set_y( ui_Switch2, -45 );
	lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );
	lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xDFB0B0), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_border_color(ui_Switch2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_border_opa(ui_Switch2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_Switch2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xC63434), LV_PART_MAIN | LV_STATE_PRESSED );
	lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN| LV_STATE_PRESSED);
	lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xB92C4C), LV_PART_MAIN | LV_STATE_FOCUSED );
	lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

	lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xEC3131), LV_PART_INDICATOR | LV_STATE_PRESSED );
	lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_INDICATOR| LV_STATE_PRESSED);

	lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x312020), LV_PART_KNOB | LV_STATE_DEFAULT );
	lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

	ui_Switch1 = lv_switch_create(ui_Screen1);
	lv_obj_set_width( ui_Switch1, 40);
	lv_obj_set_height( ui_Switch1, 20);
	lv_obj_set_x( ui_Switch1, 33 );
	lv_obj_set_y( ui_Switch1, -17 );
	lv_obj_set_align( ui_Switch1, LV_ALIGN_CENTER );
	lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xDEB1B1), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_border_color(ui_Switch1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_border_opa(ui_Switch1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_Switch1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

	lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x312020), LV_PART_KNOB | LV_STATE_DEFAULT );
	lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

	ui_Bar2 = lv_bar_create(ui_Screen1);
	lv_bar_set_value(ui_Bar2,50,LV_ANIM_OFF);
	lv_obj_set_width( ui_Bar2, 120);
	lv_obj_set_height( ui_Bar2, 10);
	lv_obj_set_x( ui_Bar2, 1 );
	lv_obj_set_y( ui_Bar2, 7 );
	lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );
	lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xE1B2B2), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_border_color(ui_Bar2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_border_opa(ui_Bar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui_Bar2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

	lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xD37373), LV_PART_INDICATOR | LV_STATE_DEFAULT );
	lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

	ui_Panel2 = lv_obj_create(ui_Screen1);
	lv_obj_set_width( ui_Panel2, 119);
	lv_obj_set_height( ui_Panel2, 41);
	lv_obj_set_x( ui_Panel2, -1 );
	lv_obj_set_y( ui_Panel2, 39 );
	lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
	lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

	ui_Button1 = lv_btn_create(ui_Screen1);
	lv_obj_set_width( ui_Button1, 100);
	lv_obj_set_height( ui_Button1, 13);
	lv_obj_set_x( ui_Button1, -1 );
	lv_obj_set_y( ui_Button1, 29 );
	lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
	lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
	lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
	lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_shadow_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui_Button1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_spread(ui_Button1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

	ui_Button2 = lv_btn_create(ui_Screen1);
	lv_obj_set_width( ui_Button2, 100);
	lv_obj_set_height( ui_Button2, 13);
	lv_obj_set_x( ui_Button2, -2 );
	lv_obj_set_y( ui_Button2, 48 );
	lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
	lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
	lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
	lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_shadow_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui_Button2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_spread(ui_Button2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

	ui_Label1 = lv_label_create(ui_Screen1);
	lv_obj_set_width( ui_Label1, 100);
	lv_obj_set_height( ui_Label1, 20);
	lv_obj_set_x( ui_Label1, 22 );
	lv_obj_set_y( ui_Label1, 32 );
	lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
	lv_label_set_text(ui_Label1,"Settings");
	lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xE8C3C3), LV_PART_MAIN | LV_STATE_DEFAULT );
	lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);
	
//	ui_list = lv_list_create(ui_Screen1);
//	lv_obj_set_size(ui_list,128,128);
//	lv_obj_center(ui_list);
//	lv_list_add_text(ui_list,"Settings");
//	
//	lv_obj_set_style_text_font(ui_list, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
//	lv_obj_t* btn1 = lv_list_add_btn(ui_list,LV_SYMBOL_WIFI,"WIFI");
//	lv_obj_t* btn2 = lv_list_add_btn(ui_list,LV_SYMBOL_GPS,"GPS");
//	lv_obj_t* btn3 = lv_list_add_btn(ui_list,LV_SYMBOL_USB,"USB");
//	lv_obj_t* btn4 = lv_list_add_btn(ui_list,LV_SYMBOL_OK,"OK");
//	lv_obj_t* btn5 = lv_list_add_btn(ui_list,LV_SYMBOL_CLOSE,"CLOSE");
	
	//lv_list_get_btn_text(ui_list,ui_Button1);
	//lv_list_get_btn_text(ui_list,ui_Button2);

}

void ui_init( void )
{
	//LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

	lv_disp_t *dispp = lv_disp_get_default();
	lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
	lv_disp_set_theme(dispp, theme);
	
	
	ui_Screen1_screen_init();
	ui____initial_actions0 = lv_obj_create(NULL);
	lv_disp_load_scr( ui_Screen1);
}
