//// This file was generated by SquareLine Studio
//// SquareLine Studio version: SquareLine Studio 1.2.3
//// LVGL version: 8.2.0
//// Project name: SquareLine_Project2


//#include "ui.h"
//#include "ui_helpers.h"
//#include "ui_comp.h"

//uint32_t LV_EVENT_GET_COMP_CHILD;

//typedef struct {
//uint32_t child_idx;
//lv_obj_t* child;
//} ui_comp_get_child_t;

//lv_obj_t * ui_comp_get_child(lv_obj_t *comp, uint32_t child_idx) {
//ui_comp_get_child_t info;
//info.child = NULL;
//info.child_idx = child_idx;
//lv_event_send(comp, LV_EVENT_GET_COMP_CHILD, &info);
// return info.child;
//}

//void get_component_child_event_cb(lv_event_t* e) {
//lv_obj_t** c = lv_event_get_user_data(e);
//ui_comp_get_child_t* info = lv_event_get_param(e);
//info->child = c[info->child_idx];
// }

//void del_component_child_event_cb(lv_event_t* e) {
//lv_obj_t** c = lv_event_get_user_data(e);
//lv_mem_free(c); 
//}


//// COMPONENT Label1

//lv_obj_t *ui_Label1_create(lv_obj_t *comp_parent) {

//lv_obj_t *cui_Label1;
//cui_Label1 = lv_label_create(comp_parent);
//lv_obj_set_width( cui_Label1, LV_SIZE_CONTENT);  /// 1
//lv_obj_set_height( cui_Label1, LV_SIZE_CONTENT);   /// 1
//lv_obj_set_x( cui_Label1, -52 );
//lv_obj_set_y( cui_Label1, -18 );
//lv_obj_set_align( cui_Label1, LV_ALIGN_CENTER );
//lv_obj_set_style_text_color(cui_Label1, lv_color_hex(0xE8C3C3), LV_PART_MAIN | LV_STATE_DEFAULT );
//lv_obj_set_style_text_opa(cui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

//lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABEL1_NUM);
//children[UI_COMP_LABEL1_LABEL1] = cui_Label1;
//lv_obj_add_event_cb(cui_Label1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
//lv_obj_add_event_cb(cui_Label1, del_component_child_event_cb, LV_EVENT_DELETE, children);
//ui_comp_Label1_create_hook(cui_Label1);
//return cui_Label1; 
//}

